"use client";
import { useEffect, useRef, useState } from "react";
const nav = [["start","Start"],["leistungen","Leistungen"],["projekte","Projekte"],["ueber","Über uns"],["kontakt","Kontakt"]];
const services = [
{title:"Renovationen",text:"Aus bestehenden Räumen wird ein neues Zuhause. Wir koordinieren Ihren Umbau – vom ersten Plan bis zum letzten Handgriff.",tags:"Innenausbau · Küche · Bad"},
{title:"Malerarbeiten",text:"Frische Farbe. Klare Kanten. Wir bringen Wände und Fassaden wieder zum Strahlen und schützen, was bleiben soll.",tags:"Innenanstrich · Fassade · Tapezieren"},
{title:"Bodenbeläge",text:"Ein guter Boden trägt den Alltag. Wir verlegen, schleifen und versiegeln mit dem richtigen Gefühl fürs Material.",tags:"Parkett · Vinyl · Fliesen"},
{title:"Fassade & Aussen",text:"Schön anzusehen. Gut geschützt. Wir machen Fassaden, Balkone und Terrassen bereit für die nächsten Jahre.",tags:"Sanierung · Dämmung · Terrasse"}];
const projects=[{title:"Mehr Raum fürs Leben.",location:"Wohnungsrenovation · Zürich-Wiedikon",image:"proj-1",alt:"Heller renovierter Wohnraum mit warmem Holzboden"},{title:"Ein neuer erster Eindruck.",location:"Fassadenrenovation · Zürich-Altstetten",image:"proj-2",alt:"Frisch renovierte Fassade eines Mehrfamilienhauses"},{title:"Der Tag beginnt hier.",location:"Badsanierung · Winterthur",image:"proj-3",alt:"Modernisiertes Badezimmer mit sorgfältig verlegten Fliesen"},{title:"Natürlich. Bodenständig.",location:"Parkettarbeiten · Küsnacht",image:"proj-4",alt:"Präzise verlegter Parkettboden in einem Wohnraum"}];
const image=(name:string)=>`/demos/handwerk/${name}.webp`;
export default function Home(){
const menuButton = useRef<HTMLButtonElement>(null);const [active,setActive]=useState("start");const [open,setOpen]=useState(false);const [previewed,setPreviewed]=useState(false);
useEffect(()=>{const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)setActive(entry.target.id)})},{rootMargin:"-15% 0px -65% 0px"});nav.forEach(([id])=>{const el=document.getElementById(id);if(el)observer.observe(el)});const escape=(event:KeyboardEvent)=>{if(event.key==="Escape"){setOpen(false);menuButton.current?.focus()}};document.addEventListener("keydown",escape);return()=>{observer.disconnect();document.removeEventListener("keydown",escape)}},[]);
return <><a className="skip" href="#inhalt">Zum Inhalt</a><aside className="sidebar"><a href="#start" className="logo" onClick={()=>setOpen(false)} aria-label="Steiner Bau – Startseite"><span className="logo-mark" aria-hidden="true">S<span>↗</span></span><span>STEINER<strong>BAU.</strong></span></a><button ref={menuButton} className="menu-button" aria-expanded={open} aria-controls="navigation" onClick={()=>setOpen(!open)}>{open?"Schliessen ×":"Menü +"}</button><nav id="navigation" aria-label="Hauptnavigation" className={open?"navigation open":"navigation"}>{nav.map(([id,label],i)=><a href={`#${id}`} key={id} aria-current={active===id?"location":undefined} onClick={()=>setOpen(false)}><span>0{i+1}</span>{label}<b aria-hidden="true">↗</b></a>)}</nav><div className="sidebar-bottom"><span className="eyebrow">Zürich & Umgebung</span><p>Gutes Handwerk.<br/>Ein gutes Gefühl.</p><a href="#kontakt" className="sidebar-cta">Projekt besprechen <span>↗</span></a><a className="portfolio-link" href="/work/steiner-handwerk">← Zurück zum Portfolio</a><small>Fiktiver Betrieb · Website-Demo</small></div></aside>
<main id="inhalt"><section id="start" className="hero"><img className="hero-image" src={image("hero-handwerk")} alt="Handwerker bei Renovationsarbeiten an einer Innenwand" fetchPriority="high"/><div className="hero-shade"/><div className="hero-top"><span>HANDWERK MIT HANDSCHLAG.</span><span className="demo-label">DEMO-PROJEKT</span></div><div className="hero-content"><p className="eyebrow"><span className="line"/>Ihr Zuhause. Unser Handwerk.</p><h1>WIR PACKEN<br/>AN. <em>SIE KOMMEN<br/>AN.</em></h1><p className="hero-description">Renovieren, umbauen, besser wohnen.<br/>Ihr Handwerksteam für Zürich und Umgebung.</p><a className="button" href="#kontakt">Ihr Projekt beginnt hier <span>↗</span></a></div><div className="hero-bottom"><span>RENOVATION · MALERARBEITEN · BODENBELÄGE</span><a href="#leistungen" aria-label="Leistungen entdecken">ENTDECKEN <span>↓</span></a></div></section>
<div className="promise-strip"><span><b>01</b> Eine Ansprechperson</span><span><b>02</b> Klare Absprachen</span><span><b>03</b> Sauber bis zum Schluss</span></div>
<section id="leistungen" className="section services-section"><div className="section-heading"><div><p className="eyebrow">01 / Unsere Leistungen</p><h2>GUTE ARBEIT.<br/><span>VON GRUND AUF.</span></h2></div><p>Ein Zimmer auffrischen oder ein ganzes Zuhause verändern: Wir denken mit und setzen um.</p></div><div className="services">{services.map((service,i)=><article key={service.title}><span className="service-number">0{i+1}</span><div><h3>{service.title}</h3><p>{service.text}</p><small>{service.tags}</small></div><a href="#kontakt" aria-label={`${service.title} besprechen`} className="service-arrow">↗</a></article>)}</div></section>
<section id="projekte" className="section projects-section"><div className="section-heading"><div><p className="eyebrow">02 / So kann es aussehen</p><h2>RÄUME MIT<br/><span>NEUEM KAPITEL.</span></h2></div><p>Von der Idee zum fertigen Raum. Eine Auswahl exemplarischer Projekte für diesen Demobetrieb.</p></div><div className="projects">{projects.map((project,i)=><article key={project.image}><div className="project-image"><img src={image(project.image)} alt={project.alt} loading="lazy" width="1000" height="750"/><span>0{i+1} / BEISPIELPROJEKT</span></div><div className="project-caption"><div><p>{project.location}</p><h3>{project.title}</h3></div><a href="#kontakt" aria-label={`Ähnliches Projekt wie ${project.title} besprechen`}>↗</a></div></article>)}</div></section>
<section id="ueber" className="section about-section"><div className="about-image"><img src={image("team")} alt="Handwerker bei sorgfältigen Spachtelarbeiten an einer Innenwand" loading="lazy" width="1000" height="1200"/><span>MIT KOPF. MIT HAND. MIT HERZ.</span></div><div><p className="eyebrow">03 / Die Menschen dahinter</p><h2>HANDWERKER.<br/><span>MITDENKER.<br/>MACHER.</span></h2><p>Ein Zuhause ist mehr als eine Baustelle. Es ist Ihr Alltag. Deshalb hören wir zuerst zu, planen gemeinsam und halten Sie während der Arbeiten auf dem Laufenden.</p><p>Unser Anspruch: Arbeiten, auf die wir stolz sind. Und Räume, in denen Sie sich wohlfühlen.</p><ul><li>Ein Team vom ersten Gespräch bis zur Übergabe</li><li>Verständliche Offerten und transparente Abläufe</li><li>Sorgfältiger Umgang mit Ihrem Zuhause</li></ul><a href="#kontakt" className="text-link">Lernen wir uns kennen <span>↗</span></a></div></section>
<section className="section process-section"><p className="eyebrow">Einfach zum fertigen Projekt</p><h2>SO GEHEN WIR’S AN.</h2><div className="process">{[["Reden.","Sie erzählen uns, was Sie vorhaben. Wir hören zu und klären die wichtigsten Fragen."],["Planen.","Wir besichtigen, besprechen Material und Ablauf und erstellen eine nachvollziehbare Offerte."],["Machen.","Unser Team legt los. Sie haben eine feste Ansprechperson – bis zur sauberen Übergabe."]].map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section id="kontakt" className="section contact-section"><div><p className="eyebrow">04 / Der erste Schritt</p><h2>WAS HABEN<br/>SIE <span>VOR?</span></h2><p>Ein frischer Anstrich? Ein neues Bad? Oder schon eine ganz konkrete Idee? So könnte Ihre Projektanfrage aussehen.</p><div className="demo-note" id="demo-hinweis"><b>Eine Website zum Ausprobieren.</b><p>Steiner Bau ist ein fiktiver Beispielbetrieb. Dieses Formular versendet und speichert keine Daten. Bitte verwenden Sie nur Testdaten.</p></div></div><form aria-describedby="demo-hinweis" onSubmit={event=>{event.preventDefault();setPreviewed(true)}}><div className="form-row"><label htmlFor="name">Ihr Name *<input id="name" name="name" required placeholder="Max Muster" autoComplete="off"/></label><label htmlFor="email">E-Mail *<input id="email" name="email" type="email" required placeholder="max@example.com" autoComplete="off"/></label></div><label htmlFor="service">Worum geht es?<select id="service" name="service"><option>Bitte wählen</option>{services.map(s=><option key={s.title}>{s.title}</option>)}<option>Etwas anderes</option></select></label><label htmlFor="message">Ihr Projekt *<textarea id="message" name="message" required rows={4} placeholder="Was möchten Sie verändern?"/></label><button className="button" type="submit">Demo-Anfrage ausprobieren <span>↗</span></button><p className="form-status" role="status">{previewed?"Demo erfolgreich ausprobiert. Es wurden keine Daten versendet oder gespeichert.":"* Pflichtfelder · Unverbindliche Formularvorschau"}</p></form></section><footer><a className="footer-brand" href="#start">STEINER BAU.</a><p>Fiktiver Beispielbetrieb · Zürich</p><a href="/work/steiner-handwerk">Zurück zum Portfolio ↗</a></footer></main></>;
}
