export const contactCopy = {
  de: {
    reason: "Worum geht es?", general: "Allgemeine Anfrage",
    reasons: { websites: "Website", presence: "Online-Präsenz", automation: "Automation" },
    nextTitle: "So geht es weiter",
    next: "Beschreiben Sie kurz Ihr Ziel und den aktuellen Stand. Ich kläre mit Ihnen, was sinnvoll und machbar ist. Umfang und Preis halten wir bei einem passenden Vorhaben in einer Offerte fest.",
    notice: "Die Anfrage ist unverbindlich. E-Mail und WhatsApp öffnen einen Entwurf; Sie ergänzen und senden die Nachricht dort selbst.",
    briefLabel: "Ihr Vorhaben (optional)",
    briefHint: "Ein paar Sätze genügen. Ihr Text bleibt bis zum Öffnen eines Kontaktwegs auf dieser Seite und wird nicht gespeichert.",
    briefPlaceholder: "Zum Beispiel: Eine Website für meinen Betrieb, mit Leistungen, Bildern und einer einfachen Anfrage.",
    briefTitle: "Mein Vorhaben",
    generalMessage: "Hallo Silvan, ich möchte ein Vorhaben mit dir besprechen.",
    scopeLabel: "Gewünschter Umfang",
    quoteRequest: "Bitte besprechen wir den passenden Umfang und eine unverbindliche Offerte.",
    copyAction: "Anfragetext kopieren",
    copied: "Anfragetext kopiert. Sie können ihn in Ihrer bevorzugten Nachrichten-App einfügen. Es wurde nichts gesendet.",
    copyFallback: "Kopieren ist hier nicht verfügbar. Markieren und kopieren Sie den Anfragetext im Feld unten.",
    draftLabel: "Ihr Anfragetext",
    draftQuestions: {
      websites: ["Das soll meine Website leisten:", "Meine bestehende Website:", "Diese Texte und Bilder sind vorhanden:"],
      presence: ["Mein Unternehmen oder bestehendes Profil:", "Das möchte ich verbessern:"],
      automation: ["Diese wiederkehrende Aufgabe möchte ich vereinfachen:", "Diese Programme nutze ich dafür:"],
    },
    prompts: {
      websites: "Für die Website: Was soll sie leisten, gibt es bereits eine Website und welche Inhalte sind vorhanden?",
      presence: "Für Ihre Online-Präsenz: Welches Unternehmen oder Profil ist betroffen und was möchten Sie verbessern?",
      automation: "Für die Automation: Welche wiederkehrende Aufgabe möchten Sie vereinfachen und welche Programme nutzen Sie dafür?",
    },
    subject: "Anfrage", message: "Hallo Silvan, ich interessiere mich für", save: "Kontakt speichern (.vcf)", explore: "Angebot und Arbeiten",
  },
  en: {
    reason: "What is your enquiry about?", general: "General enquiry",
    reasons: { websites: "Website", presence: "Online presence", automation: "Automation" },
    nextTitle: "What happens next",
    next: "Briefly describe your goal and your current situation. We will discuss what makes sense and what is feasible. If the project is a fit, its scope and price will be set out in a quote.",
    notice: "Your enquiry is non-binding. E-mail and WhatsApp open a draft; you add your details and send it there yourself.",
    briefLabel: "Your project (optional)",
    briefHint: "A few sentences are enough. Your text stays on this page until you open a contact channel and is not saved.",
    briefPlaceholder: "For example: A website for my business, with services, photographs and a simple enquiry.",
    briefTitle: "My project",
    generalMessage: "Hello Silvan, I would like to discuss a project with you.",
    scopeLabel: "Preferred scope",
    quoteRequest: "Please help me confirm the scope and prepare a no-obligation quote.",
    copyAction: "Copy enquiry text",
    copied: "Enquiry text copied. Paste it into your preferred messaging app. Nothing has been sent.",
    copyFallback: "Copying is unavailable here. Please select and copy the enquiry text in the field below.",
    draftLabel: "Your enquiry text",
    draftQuestions: {
      websites: ["What my website should achieve:", "My existing website:", "Text and images I already have:"],
      presence: ["My business or existing profile:", "What I would like to improve:"],
      automation: ["The recurring task I would like to simplify:", "The tools I currently use:"],
    },
    prompts: {
      websites: "For your website: What should it achieve, do you have an existing site and which content is ready?",
      presence: "For your online presence: Which business or profile is involved and what would you like to improve?",
      automation: "For your automation: Which recurring task would you like to simplify and which tools do you use?",
    },
    subject: "Enquiry", message: "Hello Silvan, I am interested in", save: "Save contact (.vcf)", explore: "Services and work",
  },
} as const;
