import type { SiteContent } from "./types";

export const de = {
  brand: {
    name: "SILVAN",
    descriptor: "Digital Studio",
  },
  navigation: {
    primary: [
      { label: "Websites", href: "/websites" },
      { label: "Google Reviews", href: "/reviews" },
      { label: "Online-Präsenz", href: "/presence" },
      { label: "Automation", href: "/automation" },
      { label: "Arbeiten", href: "/work" },
      { label: "Über mich", href: "/about" },
      { label: "Kontakt", href: "/contact" },
    ],
    languageLabel: "Sprache wählen",
    germanLabel: "Deutsch",
    englishLabel: "Englisch",
    openMenuLabel: "Menü öffnen",
    closeMenuLabel: "Menü schliessen",
  },
  a11y: {
    skipToContent: "Zum Inhalt springen",
    currentPage: "Aktuelle Seite",
    externalLink: "Öffnet einen externen Link",
    previousProject: "Vorheriges Projekt",
    nextProject: "Nächstes Projekt",
  },
  common: {
    learnMore: "Mehr erfahren",
    viewWork: "Arbeiten ansehen",
    getInTouch: "Kontakt aufnehmen",
    from: "ab",
    onRequest: "Auf Anfrage",
  },
  home: {
    hero: {
      serviceLine: "Websites · Google Reviews · Online-Präsenz · Automation",
      headline: "Mehr Kunden. Weniger Aufwand.",
      supporting:
        "Ich entwickle digitale Lösungen, die Ihr Unternehmen sichtbar machen und wiederkehrende Arbeit reduzieren.",
      primaryCta: "Projekt besprechen",
      secondaryCta: "Leistungen ansehen",
    },
    servicesTitle: "Digitale Lösungen für Ihr Unternehmen",
    services: [
      {
        title: "Websites",
        description: "Klare, schnelle Websites, die Ihr Angebot auf den Punkt bringen.",
        price: "ab CHF 300",
        href: "/websites",
      },
      {
        title: "Google Reviews",
        description: "NFC-Karten und Aufsteller für einen einfachen Weg zu echtem Feedback.",
        price: "ab CHF 49",
        href: "/reviews",
      },
      {
        title: "Online-Präsenz",
        description: "Ein konsistenter Auftritt, damit Ihr Unternehmen lokal leichter gefunden wird.",
        price: "ab CHF 249",
        href: "/presence",
      },
      {
        title: "Automation",
        description: "Praktische Abläufe, die wiederkehrende Aufgaben zuverlässig reduzieren.",
        price: "Auf Anfrage",
        href: "/automation",
      },
    ],
    workTitle: "Ausgewählte Arbeiten",
    studioTitle: "Direkt mit dem Entwickler arbeiten",
    studioCopy:
      "SILVAN ist das unabhängige Digital Studio von Silvan Hahn in der Schweiz. Sie erhalten klare Beratung, sorgfältiges Design und eine verlässliche Umsetzung aus einer Hand.",
  },
  websites: {
    eyebrow: "Websites",
    title: "Eine Website, die Ihr Unternehmen klar verkauft.",
    intro:
      "Von der kompakten Informationsseite bis zum individuellen grossen Auftritt: Sie erhalten eine schnelle, zugängliche und leicht pflegbare Website.",
    priceLabel: "CHF 300–5,000+",
    priceTiers: [
      {
        id: "simple",
        name: "Simple Info Website",
        price: "CHF 300–699",
        description: "Für einen fokussierten ersten Auftritt mit den wichtigsten Informationen.",
        features: ["Eine kompakte Seite", "Mobil optimiert", "Direkte Kontaktwege"],
      },
      {
        id: "standard",
        name: "Standard Business Website",
        price: "CHF 700–1,999",
        description: "Für Unternehmen, die Leistungen, Vertrauen und Kontakt klar strukturieren möchten.",
        features: ["Mehrere Inhaltsseiten", "Individuelles Layout", "Grundlegende Suchmaschinen-Basis"],
      },
      {
        id: "premium",
        name: "Premium Large Website",
        price: "CHF 2,000–4,999",
        description: "Für umfangreiche Inhalte, anspruchsvolle Gestaltung und besondere Funktionen.",
        features: ["Erweiterte Seitenstruktur", "Hochwertige Interaktionen", "Flexible Inhaltsmodule"],
      },
      {
        id: "custom",
        name: "Custom Large Project",
        price: "ab CHF 5,000",
        description: "Für individuelle digitale Projekte mit gemeinsam definiertem Umfang.",
        features: ["Massgeschneidertes Konzept", "Technische Planung", "Projektbezogene Umsetzung"],
      },
    ],
    benefitsTitle: "Was Sie erhalten",
    benefits: [
      "Eine klare Struktur für Kunden und Suchmaschinen",
      "Ein responsives Erlebnis auf jedem Bildschirm",
      "Wartbaren Code ohne unnötige technische Last",
    ],
    processTitle: "So entsteht Ihre Website",
    process: [
      { id: "understand", label: "01", title: "Verstehen", description: "Wir klären Ziele, Zielgruppen, Inhalte und den passenden Umfang." },
      { id: "design", label: "02", title: "Gestalten", description: "Ich entwickle eine klare visuelle Richtung und Seitenstruktur." },
      { id: "build", label: "03", title: "Umsetzen", description: "Design und Inhalte werden schnell, responsiv und zugänglich umgesetzt." },
      { id: "launch", label: "04", title: "Veröffentlichen", description: "Nach der gemeinsamen Prüfung geht die Website sauber online." },
    ],
    ctaLabel: "Website unverbindlich besprechen",
    ctaHref: "/contact",
  },
  reviews: {
    eyebrow: "Google Reviews",
    title: "Der direkte Weg von Ihrem Standort zu echtem Feedback.",
    intro:
      "Mit einer programmierten NFC-Karte oder einem Aufsteller öffnen Ihre Kunden Ihre Google-Bewertungsseite mit einer Berührung.",
    priceLabel: "Produkte inklusive Einrichtung",
    products: [
      {
        id: "card",
        name: "NFC Review Card",
        price: "CHF 49",
        description: "Eine Karte inklusive Programmierung und Einrichtung.",
        features: ["NFC-fähig", "Eingerichtet für Ihr Profil", "Sofort einsatzbereit"],
      },
      {
        id: "stand",
        name: "NFC Stand",
        price: "CHF 69",
        description: "Ein sichtbarer Aufsteller für Empfang, Kasse oder Tisch.",
        features: ["NFC-fähig", "Stabiler Aufsteller", "Inklusive Einrichtung"],
      },
      {
        id: "two-cards",
        name: "Zwei NFC Review Cards",
        price: "CHF 80",
        description: "Zwei eingerichtete Karten für mehrere Kontaktpunkte.",
        features: ["Zwei Karten", "Ein Google-Profil", "Inklusive Einrichtung"],
      },
    ],
    quantityDiscount: "Für grössere Mengen ist ein Mengenrabatt verfügbar.",
    processTitle: "Drei einfache Schritte",
    process: [
      { id: "tap", label: "TAP", title: "Berühren", description: "Der Kunde berührt die NFC-Karte oder den Aufsteller mit dem Smartphone." },
      { id: "open", label: "OPEN", title: "Öffnen", description: "Die Google-Bewertungsseite Ihres Unternehmens öffnet sich direkt." },
      { id: "review", label: "REVIEW", title: "Bewerten", description: "Der Kunde hinterlässt freiwillig sein ehrliches Feedback." },
    ],
    ctaLabel: "Unverbindlich anfragen",
    productImageAlt: "NFC Review Card und Aufsteller für Google-Bewertungen",
    inquiry: {
      title: "Review Card anfragen",
      intro: "Senden Sie die Eckdaten direkt per WhatsApp. Ich melde mich persönlich bei Ihnen.",
      fields: [
        { name: "product", label: "Produkt", placeholder: "Produkt wählen", required: true },
        { name: "quantity", label: "Menge", placeholder: "Zum Beispiel 2", required: true },
        { name: "variant", label: "Farbe oder Variante", placeholder: "Gewünschte Variante", required: true },
        { name: "businessName", label: "Unternehmen", placeholder: "Name Ihres Unternehmens", required: true },
        { name: "contactPerson", label: "Kontaktperson", placeholder: "Vor- und Nachname", required: true },
        { name: "googleUrl", label: "Google-Unternehmensprofil oder Bewertungslink", placeholder: "https://…", required: true },
        { name: "street", label: "Strasse", placeholder: "Strasse und Hausnummer", required: true },
        { name: "postalCode", label: "PLZ", placeholder: "8000", required: true },
        { name: "city", label: "Ort", placeholder: "Zürich", required: true },
        { name: "note", label: "Optionale Nachricht", placeholder: "Was sollte ich noch wissen?", required: false },
      ],
      productOptions: { card: "NFC Review Card", stand: "NFC Stand" },
      submitLabel: "Anfrage in WhatsApp öffnen",
      editLabel: "Angaben bearbeiten",
      requiredError: "Bitte füllen Sie dieses Feld aus.",
      quantityError: "Bitte geben Sie eine gültige Menge ab 1 ein.",
      urlError: "Bitte geben Sie einen gültigen Google-Link ein.",
      nonBindingNotice: "Dies ist eine unverbindliche Anfrage. Sie wird erst nach meiner persönlichen Bestätigung verbindlich.",
      privacyNotice: "Ihre Angaben werden nicht auf dieser Website gespeichert, sondern nur in die WhatsApp-Nachricht eingefügt.",
      messageIntro: "Hallo Silvan, ich möchte unverbindlich NFC Review Cards anfragen.",
    },
  },
  presence: {
    eyebrow: "Online-Präsenz",
    title: "Damit Ihr Unternehmen dort stimmt, wo Kunden suchen.",
    intro:
      "Ich richte Ihr Google-Unternehmensprofil ein oder optimiere es und sorge für konsistente, verständliche Geschäftsinformationen.",
    priceLabel: "ab CHF 249",
    startingPrice: "ab CHF 249",
    priceTiers: [
      {
        id: "profile",
        name: "Google Business Profile Basis",
        price: "ab CHF 249",
        description: "Ein sauber eingerichtetes Profil als Grundlage für Ihre lokale Sichtbarkeit.",
        features: ["Profilprüfung oder Einrichtung", "Konsistente Geschäftsdaten", "Klare Leistungsinformationen"],
      },
    ],
    benefitsTitle: "Für einen verlässlichen lokalen Auftritt",
    benefits: [
      "Ihr Unternehmen ist mit korrekten Angaben auffindbar",
      "Öffnungszeiten und Kontaktwege sind konsistent",
      "Kunden verstehen schneller, was Sie anbieten",
    ],
    processTitle: "So gehen wir vor",
    process: [
      { id: "audit", label: "01", title: "Prüfen", description: "Ich prüfe den aktuellen Auftritt und erkennbare Lücken." },
      { id: "align", label: "02", title: "Abgleichen", description: "Wir klären Leistungen, Zielgebiet und korrekte Geschäftsdaten." },
      { id: "optimize", label: "03", title: "Optimieren", description: "Profil und Informationen werden nachvollziehbar verbessert." },
      { id: "handover", label: "04", title: "Übergeben", description: "Sie erhalten einen klaren Überblick und die nächsten sinnvollen Schritte." },
    ],
    ctaLabel: "Online-Präsenz besprechen",
    ctaHref: "/contact",
  },
  automation: {
    eyebrow: "Automation",
    title: "Wiederkehrende Arbeit auf einen klaren Ablauf bringen.",
    intro:
      "Ich untersuche manuelle Routinen und entwickle passende Automationen für E-Mails, Berichte, Informationsübergaben und interne Abläufe.",
    priceLabel: "Auf Anfrage",
    priceTiers: [
      {
        id: "custom-automation",
        name: "Individuelle Automation",
        price: "Auf Anfrage",
        description: "Umfang und Lösung richten sich nach Ihrem bestehenden Prozess und den technisch sinnvollen Möglichkeiten.",
        features: ["Machbarkeitsprüfung", "Gezielte Umsetzung", "Dokumentierte Übergabe"],
      },
    ],
    benefitsTitle: "Geeignete Aufgaben",
    benefits: [
      "Wiederkehrende E-Mails und Benachrichtigungen",
      "Regelmässige Berichte und Datenaufbereitung",
      "Informationsübergaben und wiederholbare interne Workflows",
    ],
    processTitle: "Vom Engpass zur Lösung",
    process: [
      { id: "discover", label: "01", title: "Entdecken", description: "Wir machen den heutigen Ablauf und seinen Zeitaufwand sichtbar." },
      { id: "assess", label: "02", title: "Prüfen", description: "Ich beurteile Machbarkeit, Risiken und den erwartbaren Nutzen." },
      { id: "implement", label: "03", title: "Umsetzen", description: "Die passende Lösung wird schrittweise eingerichtet und getestet." },
      { id: "handover", label: "04", title: "Übergeben", description: "Sie erhalten eine verständliche Einführung und Dokumentation." },
    ],
    ctaLabel: "Ablauf unverbindlich prüfen",
    ctaHref: "/contact",
  },
  work: {
    eyebrow: "Arbeiten",
    title: "Digitale Konzepte mit klarer Funktion.",
    intro: "Ausgewählte Gestaltungskonzepte zeigen, wie Strategie, Inhalt und Entwicklung zusammenwirken können.",
    conceptLabel: "Konzeptprojekt",
    projectInfoLabel: "Projektinformationen",
    challengeLabel: "Aufgabe",
    approachLabel: "Ansatz",
    outcomeLabel: "Beabsichtigtes Ergebnis",
  },
  about: {
    eyebrow: "Über mich",
    title: "Direkte Zusammenarbeit, sorgfältig umgesetzt.",
    intro: "Ich bin Silvan Hahn, unabhängiger Digital Developer in der Schweiz.",
    body: [
      "Ich verbinde klare Gestaltung mit wartbarer Entwicklung und konzentriere mich auf digitale Lösungen, die im Alltag tatsächlich helfen.",
      "Sie sprechen direkt mit der Person, die Ihr Projekt plant und umsetzt. So bleiben Entscheidungen verständlich, Wege kurz und der Umfang realistisch.",
    ],
    valuesTitle: "Arbeitsweise",
    values: [
      { title: "Klar", description: "Ziele, Umfang und Entscheidungen bleiben nachvollziehbar." },
      { title: "Direkt", description: "Sie arbeiten ohne Übergaben zwischen Verkauf, Design und Entwicklung." },
      { title: "Praktisch", description: "Die Lösung orientiert sich an Ihrem Betrieb, nicht an kurzlebigen Trends." },
    ],
    portraitAlt: "Platzhalter für ein zukünftiges Porträt von Silvan Hahn",
    portraitStatus: "Ersetzbarer Bildplatzhalter – kein Foto von Silvan Hahn",
  },
  contact: {
    eyebrow: "Kontakt",
    title: "Lassen Sie uns Ihr Vorhaben besprechen.",
    intro: "Schreiben Sie mir direkt per E-Mail oder WhatsApp. Telefon und LinkedIn sind ebenfalls erreichbar.",
    emailLabel: "E-Mail",
    phoneLabel: "Telefon",
    whatsappLabel: "WhatsApp",
    linkedInLabel: "LinkedIn",
    details: {
      email: "hahn.silvan.work@gmail.com",
      phoneDisplay: "078 900 85 00",
      phoneHref: "tel:+41789008500",
      whatsappNumber: "+41789008500",
      whatsappHref: "https://wa.me/41789008500",
      linkedIn: "https://www.linkedin.com/in/silvan-hahn-dev",
    },
  },
  hello: {
    eyebrow: "SILVAN Digital Studio",
    title: "Hallo, ich bin Silvan.",
    intro: "Websites, lokale Sichtbarkeit und praktische Automationen für Schweizer Unternehmen.",
    links: [
      { label: "Websites", href: "/websites" },
      { label: "Google Reviews", href: "/reviews" },
      { label: "Online-Präsenz", href: "/presence" },
      { label: "Arbeiten", href: "/work" },
      { label: "Über mich", href: "/about" },
      { label: "Kontakt", href: "/contact" },
    ],
    directContactTitle: "Direkt erreichen",
  },
  notFound: {
    eyebrow: "404",
    title: "Diese Seite wurde nicht gefunden.",
    description: "Der Link ist möglicherweise veraltet oder die Adresse wurde falsch eingegeben.",
    homeLabel: "Zur Startseite",
  },
  seo: {
    home: { title: "SILVAN Digital Studio | Digitale Lösungen für Schweizer Unternehmen", description: "Websites, Google Reviews, Online-Präsenz und Automation – klar entwickelt für Schweizer Unternehmen." },
    websites: { title: "Websites für Schweizer Unternehmen | SILVAN", description: "Schnelle, klare Business-Websites von CHF 300 bis zum individuellen grossen Projekt." },
    reviews: { title: "NFC Google Review Cards | SILVAN", description: "NFC Review Cards und Aufsteller inklusive Einrichtung ab CHF 49 für einen einfachen Weg zu ehrlichem Kundenfeedback." },
    presence: { title: "Online-Präsenz & Google Business Profile | SILVAN", description: "Google-Unternehmensprofil, konsistente Geschäftsdaten und lokale Sichtbarkeit ab CHF 249." },
    automation: { title: "Praktische Business-Automation | SILVAN", description: "Wiederkehrende E-Mails, Berichte und interne Abläufe sinnvoll automatisieren." },
    work: { title: "Arbeiten & digitale Konzepte | SILVAN", description: "Ausgewählte Website- und Digitalkonzepte von SILVAN Digital Studio." },
    about: { title: "Über Silvan Hahn | SILVAN Digital Studio", description: "Lernen Sie Silvan Hahn kennen, unabhängiger Digital Developer in der Schweiz." },
    contact: { title: "Kontakt | SILVAN Digital Studio", description: "Kontaktieren Sie Silvan Hahn direkt per E-Mail, WhatsApp, Telefon oder LinkedIn." },
    hello: { title: "Hallo, ich bin Silvan | SILVAN Digital Studio", description: "Der direkte Einstieg zu Websites, Google Reviews, Online-Präsenz, Arbeiten und Kontakt." },
  },
} satisfies SiteContent;
