import type { SiteContent } from "./types";

export const en = {
  brand: {
    name: "SILVAN",
    descriptor: "Digital Studio",
  },
  navigation: {
    primary: [
      { label: "Websites", href: "/websites" },
      { label: "Google Reviews", href: "/reviews" },
      { label: "Online Presence", href: "/presence" },
      { label: "Automation", href: "/automation" },
      { label: "Work", href: "/work" },
      { label: "About", href: "/about" },
      { label: "Contact", href: "/contact" },
    ],
    languageLabel: "Choose language",
    germanLabel: "German",
    englishLabel: "English",
    openMenuLabel: "Open menu",
    closeMenuLabel: "Close menu",
  },
  a11y: {
    skipToContent: "Skip to content",
    currentPage: "Current page",
    externalLink: "Opens an external link",
    previousProject: "Previous project",
    nextProject: "Next project",
  },
  common: {
    learnMore: "Learn more",
    viewWork: "View work",
    getInTouch: "Get in touch",
    from: "from",
    onRequest: "On request",
  },
  home: {
    hero: {
      serviceLine: "Websites · Google Reviews · Online Presence · Automation",
      headline: "More customers. Less busywork.",
      supporting:
        "I build digital solutions that help people find your business and take recurring work off your plate.",
      primaryCta: "Discuss a project",
      secondaryCta: "Explore services",
    },
    servicesTitle: "Digital solutions for your business",
    services: [
      {
        title: "Websites",
        description: "Clear, fast websites that make your offer easy to understand.",
        price: "from CHF 300",
        href: "/websites",
      },
      {
        title: "Google Reviews",
        description: "NFC cards and stands that make genuine feedback easier to leave.",
        price: "from CHF 49",
        href: "/reviews",
      },
      {
        title: "Online Presence",
        description: "A consistent presence that makes your business easier to find locally.",
        price: "from CHF 249",
        href: "/presence",
      },
      {
        title: "Automation",
        description: "Practical workflows that reliably reduce repetitive tasks.",
        price: "On request",
        href: "/automation",
      },
    ],
    workTitle: "Selected work",
    studioTitle: "Work directly with the developer",
    studioCopy:
      "SILVAN is Silvan Hahn's independent digital studio in Switzerland. You get clear advice, considered design, and dependable delivery from one person.",
  },
  websites: {
    eyebrow: "Websites",
    title: "A website that makes your business easy to choose.",
    intro:
      "From a focused information site to a large custom presence, you get a fast, accessible website that is straightforward to maintain.",
    priceLabel: "CHF 300–5,000+",
    priceTiers: [
      {
        id: "simple",
        name: "Simple Info Website",
        price: "CHF 300–699",
        description: "A focused first presence with the essential information customers need.",
        features: ["One concise page", "Mobile optimized", "Direct contact options"],
      },
      {
        id: "standard",
        name: "Standard Business Website",
        price: "CHF 700–1,999",
        description: "For businesses ready to structure services, trust signals, and contact clearly.",
        features: ["Multiple content pages", "Custom layout", "Essential search foundations"],
      },
      {
        id: "premium",
        name: "Premium Large Website",
        price: "CHF 2,000–4,999",
        description: "For substantial content, ambitious design, and more advanced functionality.",
        features: ["Expanded site structure", "Polished interactions", "Flexible content modules"],
      },
      {
        id: "custom",
        name: "Custom Large Project",
        price: "from CHF 5,000",
        description: "For bespoke digital projects with a scope we define together.",
        features: ["Tailored concept", "Technical planning", "Project-specific delivery"],
      },
    ],
    benefitsTitle: "What you get",
    benefits: [
      "A clear structure for customers and search engines",
      "A responsive experience on every screen",
      "Maintainable code without unnecessary technical weight",
    ],
    processTitle: "How your website takes shape",
    process: [
      { id: "understand", label: "01", title: "Understand", description: "We clarify the goals, audience, content, and right scope." },
      { id: "design", label: "02", title: "Design", description: "I develop a clear visual direction and page structure." },
      { id: "build", label: "03", title: "Build", description: "The design and content become a fast, responsive, accessible website." },
      { id: "launch", label: "04", title: "Launch", description: "After a shared review, the website goes live cleanly." },
    ],
    ctaLabel: "Discuss your website",
    ctaHref: "/contact",
  },
  reviews: {
    eyebrow: "Google Reviews",
    title: "A direct route from your location to genuine feedback.",
    intro:
      "A programmed NFC card or stand opens your Google review page when a customer taps it with their phone.",
    priceLabel: "Products including setup",
    products: [
      {
        id: "card",
        name: "NFC Review Card",
        price: "CHF 49",
        description: "One card, programmed and set up for your business.",
        features: ["NFC enabled", "Connected to your profile", "Ready to use"],
      },
      {
        id: "stand",
        name: "NFC Stand",
        price: "CHF 69",
        description: "A visible stand for your reception, counter, or table.",
        features: ["NFC enabled", "Stable display stand", "Setup included"],
      },
      {
        id: "two-cards",
        name: "Two NFC Review Cards",
        price: "CHF 80",
        description: "Two configured cards for more than one customer touchpoint.",
        features: ["Two cards", "One Google profile", "Setup included"],
      },
    ],
    quantityDiscount: "Quantity discounts are available for larger orders.",
    processTitle: "Three simple steps",
    process: [
      { id: "tap", label: "TAP", title: "Tap", description: "The customer taps the NFC card or stand with their phone." },
      { id: "open", label: "OPEN", title: "Open", description: "Your business's Google review page opens directly." },
      { id: "review", label: "REVIEW", title: "Review", description: "The customer chooses to leave their honest feedback." },
    ],
    ctaLabel: "Make a no-obligation inquiry",
    productImageAlt: "NFC review card and stand for Google reviews",
    inquiry: {
      title: "Ask about Review Cards",
      intro: "Send the essentials through WhatsApp and I will respond personally.",
      fields: [
        { name: "product", label: "Product", placeholder: "Choose a product", required: true },
        { name: "quantity", label: "Quantity", placeholder: "For example, 2", required: true },
        { name: "variant", label: "Colour or variant", placeholder: "Preferred variant", required: true },
        { name: "businessName", label: "Business", placeholder: "Your business name", required: true },
        { name: "contactPerson", label: "Contact person", placeholder: "First and last name", required: true },
        { name: "googleUrl", label: "Google Business Profile or review link", placeholder: "https://…", required: true },
        { name: "street", label: "Street", placeholder: "Street and number", required: true },
        { name: "postalCode", label: "Postcode", placeholder: "8000", required: true },
        { name: "city", label: "Town or city", placeholder: "Zurich", required: true },
        { name: "note", label: "Optional note", placeholder: "Anything else I should know?", required: false },
      ],
      productOptions: { card: "NFC Review Card", stand: "NFC Stand" },
      submitLabel: "Open inquiry in WhatsApp",
      editLabel: "Edit details",
      requiredError: "Please complete this field.",
      quantityError: "Please enter a valid quantity of at least 1.",
      urlError: "Please enter a valid Google link.",
      nonBindingNotice: "This is a no-obligation inquiry. It only becomes binding after I personally confirm it.",
      privacyNotice: "Your details are not stored by this website; they are only inserted into the WhatsApp message.",
      messageIntro: "Hi Silvan, I would like to make a no-obligation inquiry about NFC Review Cards.",
    },
  },
  presence: {
    eyebrow: "Online Presence",
    title: "Get the details right wherever customers find you.",
    intro:
      "I set up or improve your Google Business Profile and make sure your core business information is consistent and easy to understand.",
    priceLabel: "from CHF 249",
    startingPrice: "from CHF 249",
    priceTiers: [
      {
        id: "profile",
        name: "Google Business Profile Foundation",
        price: "from CHF 249",
        description: "A properly configured profile that gives your local visibility a solid foundation.",
        features: ["Profile audit or setup", "Consistent business details", "Clear service information"],
      },
    ],
    benefitsTitle: "A dependable local presence",
    benefits: [
      "Customers can find your business with accurate details",
      "Opening hours and contact options stay consistent",
      "People understand your offer more quickly",
    ],
    processTitle: "How we approach it",
    process: [
      { id: "audit", label: "01", title: "Audit", description: "I review your current presence and identify visible gaps." },
      { id: "align", label: "02", title: "Align", description: "We confirm your services, local area, and correct business details." },
      { id: "optimize", label: "03", title: "Improve", description: "The profile and information are improved in a clear, accountable way." },
      { id: "handover", label: "04", title: "Handover", description: "You receive a clear overview and practical next steps." },
    ],
    ctaLabel: "Discuss your online presence",
    ctaHref: "/contact",
  },
  automation: {
    eyebrow: "Automation",
    title: "Turn recurring work into a clear, reliable workflow.",
    intro:
      "I examine manual routines and build sensible automations for emails, reports, information handoffs, and internal processes.",
    priceLabel: "On request",
    priceTiers: [
      {
        id: "custom-automation",
        name: "Custom Automation",
        price: "On request",
        description: "The scope and solution depend on your current process and what is technically worthwhile.",
        features: ["Feasibility assessment", "Focused implementation", "Documented handover"],
      },
    ],
    benefitsTitle: "Good candidates for automation",
    benefits: [
      "Recurring emails and notifications",
      "Regular reports and data preparation",
      "Information handoffs and repeatable internal workflows",
    ],
    processTitle: "From bottleneck to solution",
    process: [
      { id: "discover", label: "01", title: "Discover", description: "We map the current process and the time it consumes." },
      { id: "assess", label: "02", title: "Assess", description: "I evaluate feasibility, risks, and the realistic benefit." },
      { id: "implement", label: "03", title: "Implement", description: "The right solution is introduced and tested step by step." },
      { id: "handover", label: "04", title: "Handover", description: "You receive a straightforward introduction and documentation." },
    ],
    ctaLabel: "Request a workflow review",
    ctaHref: "/contact",
  },
  work: {
    eyebrow: "Work",
    title: "Digital concepts with a clear purpose.",
    intro: "Selected design concepts show how strategy, content, and development can work together.",
    conceptLabel: "Concept project",
    projectInfoLabel: "Project information",
    challengeLabel: "Challenge",
    approachLabel: "Approach",
    outcomeLabel: "Intended outcome",
  },
  about: {
    eyebrow: "About",
    title: "Direct collaboration, carefully delivered.",
    intro: "I'm Silvan Hahn, an independent digital developer based in Switzerland.",
    body: [
      "I combine clear design with maintainable development, focusing on digital solutions that are genuinely useful in day-to-day business.",
      "You work directly with the person planning and building your project. Decisions stay understandable, communication stays short, and the scope stays realistic.",
    ],
    valuesTitle: "How I work",
    values: [
      { title: "Clear", description: "Goals, scope, and decisions stay easy to follow." },
      { title: "Direct", description: "There are no handoffs between sales, design, and development." },
      { title: "Practical", description: "The solution fits your business rather than a short-lived trend." },
    ],
    portraitAlt: "Placeholder for a future portrait of Silvan Hahn",
    portraitStatus: "Replaceable image placeholder — not a photograph of Silvan Hahn",
  },
  contact: {
    eyebrow: "Contact",
    title: "Let's talk about what you need.",
    intro: "Email or message me directly on WhatsApp. You can also reach me by phone or on LinkedIn.",
    emailLabel: "Email",
    phoneLabel: "Phone",
    whatsappLabel: "WhatsApp",
    linkedInLabel: "LinkedIn",
    details: {
      email: "hahn.silvan.work@gmail.com",
      phoneDisplay: "078 900 85 00",
      phoneHref: "tel:+41789008500",
      whatsappNumber: "+41789008500",
      whatsappHref: "https://wa.me/41789008500",
      linkedIn: "https://www.linkedin.com/in/silvan-hahn-dev",
    },
  },
  hello: {
    eyebrow: "SILVAN Digital Studio",
    title: "Hi, I'm Silvan.",
    intro: "Websites, local visibility, and practical automation for Swiss businesses.",
    links: [
      { label: "Websites", href: "/websites" },
      { label: "Google Reviews", href: "/reviews" },
      { label: "Online Presence", href: "/presence" },
      { label: "Work", href: "/work" },
      { label: "About", href: "/about" },
      { label: "Contact", href: "/contact" },
    ],
    directContactTitle: "Contact me directly",
  },
  notFound: {
    eyebrow: "404",
    title: "This page could not be found.",
    description: "The link may be outdated, or the address may have been entered incorrectly.",
    homeLabel: "Back to home",
  },
  seo: {
    home: { title: "SILVAN Digital Studio | Digital Solutions for Swiss Businesses", description: "Websites, Google Reviews, online presence, and automation, clearly built for Swiss businesses." },
    websites: { title: "Websites for Swiss Businesses | SILVAN", description: "Fast, clear business websites from CHF 300 through to large custom projects." },
    reviews: { title: "NFC Google Review Cards | SILVAN", description: "NFC review cards and stands with setup included from CHF 49, making genuine customer feedback easier." },
    presence: { title: "Online Presence & Google Business Profile | SILVAN", description: "Google Business Profile setup, consistent business details, and local visibility from CHF 249." },
    automation: { title: "Practical Business Automation | SILVAN", description: "Make recurring emails, reports, and internal workflows more efficient with practical automation." },
    work: { title: "Work & Digital Concepts | SILVAN", description: "Selected website and digital concepts from SILVAN Digital Studio." },
    about: { title: "About Silvan Hahn | SILVAN Digital Studio", description: "Meet Silvan Hahn, an independent digital developer based in Switzerland." },
    contact: { title: "Contact | SILVAN Digital Studio", description: "Contact Silvan Hahn directly by email, WhatsApp, phone, or LinkedIn." },
    hello: { title: "Hi, I'm Silvan | SILVAN Digital Studio", description: "A direct route to websites, Google Reviews, online presence, work, and contact." },
  },
} as const satisfies SiteContent;
