import type { LegalContent, Locale } from "./types";
import { measurementCopy } from "./measurement-copy";

// Account-specific evidence and contract drafts belong in docs/legal, never in public placeholders.
export const imprintContent: Record<Locale, LegalContent> = {
  de: {
    eyebrow: "Impressum", title: "Wer hinter dieser Website steht.",
    intro: "Anbieterkennzeichnung und Hinweise zum Angebot von SILVAN Digital Studio.",
    updatedLabel: "Stand", updated: "7. September 2026",
    sections: [
      { title: "Anbieter und Kontakt", body: ["Silvan Hahn · SILVAN Digital Studio", "Regensbergstrasse 23", "8113 Boppelsen, Schweiz", "E-Mail: hahn.silvan.work@gmail.com", "Telefon: +41 78 900 85 00", "SILVAN Digital Studio ist die Geschäftsbezeichnung, unter der Silvan Hahn die hier beschriebenen Leistungen anbietet."] },
      { title: "Anfragen und Vertragsschluss", body: ["Diese Website stellt Leistungen und Produkte vor. Es gibt keinen Online-Checkout. Eine Konfiguration, das Öffnen eines Kontaktlinks oder das Versenden einer Anfrage ist noch keine kostenpflichtige Bestellung.", "Leistungsumfang, Gesamtpreis, allfällige Versand- und laufende Kosten, Termine und weitere Vertragsbedingungen werden in einer individuellen Offerte festgehalten. Ein Auftrag entsteht durch die übereinstimmende Annahme des vereinbarten Angebots. Abweichende oder zusätzliche Leistungen bedürfen einer Vereinbarung."] },
      { title: "Preise und Leistungsumfang", body: ["Preise werden in Schweizer Franken (CHF) angegeben. Die dargestellten Preisstufen beschreiben den angegebenen Umfang; individuelle Zusatzleistungen werden separat offeriert. Die auf der Website genannten Beträge enthalten allfällige gesetzlich geschuldete Abgaben. Versandkosten für physische Produkte werden abhängig von Lieferort und Umfang vor der Bestellung gesondert ausgewiesen.", "Domain, Hosting, externe Abonnements sowie laufende Wartung sind nur enthalten, wenn dies ausdrücklich angegeben oder in der Offerte vereinbart ist. Bei NFC-Produkten ist die beschriebene Linkeinrichtung enthalten; die Erstellung einer neuen Zielwebsite oder ein kostenpflichtiger Buchungsdienst gehören nicht automatisch dazu."] },
      { title: "Konzeptprojekte und Demos", body: ["Die Portfolioarbeiten Falkenried, Café & Konditorei Vogel, Steiner Bau und Salon Lumière sind fiktive, eigeninitiierte Konzeptprojekte. Sie belegen Gestaltung und Funktion, keine Kundenbeziehung, Kundenaussage oder Geschäftsergebnisse.", "Demoformulare dienen ausschliesslich zum Ausprobieren mit Testdaten. Sie nehmen keine Bestellungen, Reservierungen oder tatsächlichen Projektanfragen entgegen. Für Anfragen an Silvan Hahn nutzen Sie die Kontaktwege dieser Website."] },
      { title: "Bewertungen und Marken", body: ["NFC- und QR-Produkte erleichtern den Zugang zu einer Zielseite. Sie kaufen damit keine Bewertungen oder bestimmte Sternezahl. Bewertungen müssen auf echten Erfahrungen beruhen und frei erfolgen; Gegenleistungen und das gezielte Ausfiltern unzufriedener Kunden sind nicht Bestandteil des Angebots.", "Genannte Marken gehören ihren jeweiligen Rechteinhabern. Die Nennung von Google, WhatsApp oder anderen Diensten beschreibt die vorgesehene Nutzung und behauptet keine Partnerschaft oder Zertifizierung durch diese Anbieter."] },
      { title: "Inhalte, externe Angebote und Rechte", body: ["Die Inhalte werden mit Sorgfalt erstellt. Offensichtliche Fehler können berichtigt werden; gesetzliche Rechte und verbindlich vereinbarte Leistungen bleiben davon unberührt. Externe Anbieter verantworten ihre eigenen Angebote und können deren Funktionen und Bedingungen ändern.", "Eigene Texte, Gestaltungen und Bilder sind im gesetzlich vorgesehenen Umfang geschützt. Inhalte Dritter unterliegen den Rechten und Lizenzen ihrer jeweiligen Rechteinhaber. Gesetzlich erlaubte Nutzungen bleiben zulässig. Nutzungsrechte an Kundenprojekten werden im jeweiligen Auftrag geregelt."] },
    ],
  },
  en: {
    eyebrow: "Imprint", title: "Who is behind this website.",
    intro: "Provider identification and information about the SILVAN Digital Studio offer.",
    updatedLabel: "Updated", updated: "7 September 2026",
    sections: [
      { title: "Provider and contact", body: ["Silvan Hahn · SILVAN Digital Studio", "Regensbergstrasse 23", "8113 Boppelsen, Switzerland", "Email: hahn.silvan.work@gmail.com", "Phone: +41 78 900 85 00", "SILVAN Digital Studio is the trading name under which Silvan Hahn offers the services described here."] },
      { title: "Enquiries and contract formation", body: ["This website presents services and products. There is no online checkout. Configuring a product, opening a contact link or sending an enquiry does not place a paid order.", "An individual quote sets out the scope, total price, any shipping and recurring costs, schedule and other contractual conditions. A contract arises through mutual acceptance of the agreed offer. Changes and additional services require agreement."] },
      { title: "Prices and scope", body: ["Prices are stated in Swiss francs (CHF). The displayed tiers cover the scope described; individual additional services are quoted separately. Website prices include any legally applicable charges. Shipping for physical products is quoted separately before ordering, depending on the destination and order size.", "Domain, hosting, external subscriptions and ongoing maintenance are included only where expressly stated or agreed in the quote. NFC products include the link setup described; creating a new destination website or a paid booking service is not automatically included."] },
      { title: "Concept projects and demos", body: ["The Falkenried, Café & Konditorei Vogel, Steiner Bau and Salon Lumière portfolio projects are fictional, self-initiated concepts. They demonstrate design and functionality, not client relationships, endorsements or business results.", "Demo forms are solely for experimenting with test data. They do not accept orders, reservations or actual project enquiries. To contact Silvan Hahn, use this website's contact channels."] },
      { title: "Reviews and trademarks", body: ["NFC and QR products make it easier to reach a destination page. They do not purchase reviews or a particular star rating. Reviews must reflect real experiences and be freely given; incentives and filtering out dissatisfied customers are not part of the offer.", "Trademarks belong to their respective owners. References to Google, WhatsApp or other services describe the intended use and do not imply a partnership or certification by those providers."] },
      { title: "Content, external services and rights", body: ["Content is prepared with care. Obvious errors may be corrected; statutory rights and binding contractual commitments remain unaffected. External providers are responsible for their own services and may change their features and terms.", "Original text, design and images are protected to the extent provided by law. Third-party material remains subject to its owners' rights and licences. Uses permitted by law remain permitted. Rights in client projects are agreed in each individual contract."] },
    ],
  },
};

export const privacyContent: Record<Locale, LegalContent> = {
  de: {
    eyebrow: "Datenschutz", title: "Welche Daten bearbeitet werden.",
    intro: "Informationen nach dem Schweizer Datenschutzgesetz (DSG) zum Besuch dieser Website, ihrer Konzept-Demos und zur Kontaktaufnahme mit SILVAN Digital Studio.",
    updatedLabel: "Stand", updated: "7. September 2026",
    sections: [
      { title: "Verantwortlicher und Geltungsbereich", body: ["Silvan Hahn, Regensbergstrasse 23, 8113 Boppelsen, Schweiz. Für Datenschutzanliegen: hahn.silvan.work@gmail.com.", "Diese Erklärung betrifft silvandigital.ch sowie die von hier verlinkten SILVAN-Konzept-Demos Falkenried, Café & Konditorei Vogel, Steiner Bau und Salon Lumière auf deren Vercel-Adressen. Für später vereinbarte Kundenprojekte können zusätzliche, projektspezifische Informationen erforderlich sein."] },
      { title: "Zwecke und notwendige Angaben", body: ["Daten werden bearbeitet, um die Website sicher auszuliefern, Anfragen zu beantworten, Offerten zu erstellen, vereinbarte Leistungen abzuwickeln und gesetzliche Pflichten zu erfüllen. Sie müssen keine Anfrage stellen, um die Website anzusehen. Ohne notwendige Kontakt- und Projektangaben kann eine gewünschte Offerte oder Leistung gegebenenfalls nicht erstellt werden.", "Die Website hat keine Benutzerkonten, keine Kommentarfunktion und keine Kundendatenbank. Es findet keine automatisierte Entscheidung mit rechtlicher Wirkung über Sie statt. Bitte übermitteln Sie über allgemeine Kontaktwege keine Passwörter, Ausweiskopien, Gesundheitsdaten oder sonstigen vertraulichen Kundendaten."] },
      { title: "Hosting und technische Zugriffsdaten", body: ["Die Website und Demos werden von Vercel Inc., USA, über ein Verteilnetz ausgeliefert. Bei einem Aufruf werden insbesondere IP-Adresse, Zeitpunkt, angefragte Adresse, technische Browser-/Geräteangaben und gegebenenfalls der verweisende Ursprung verarbeitet. Dies dient der Bereitstellung, Fehleranalyse und Abwehr missbräuchlicher Zugriffe.", "Dabei kann eine Bearbeitung in den USA stattfinden. Vercel beschreibt in seinen Anbieterinformationen internationale Infrastruktur und seine Teilnahme am Swiss-U.S. Data Privacy Framework. Die konkrete Bearbeitung richtet sich zusätzlich nach dem genutzten Dienst und dessen Vertragsbedingungen."], links: [{ label: "Datenschutzhinweise von Vercel", href: "https://vercel.com/legal/privacy-notice" }] },
      { title: "Cookies, lokale Speicherung und Schriften", body: ["Die eigene Website setzt keine Cookies zur Werbung oder Profilbildung und speichert keine Anfragetexte in localStorage. Ausschliesslich beim bewussten Sprachwechsel im selben Tab wird der NFC-Anfrageentwurf einmalig in sessionStorage zur Übergabe hinterlegt: höchstens zwei Minuten gültig und beim nächsten Übernahmeversuch gelöscht. Nicht übernommene Daten werden beim Schliessen des Tabs gelöscht. Es gibt kein automatisches Speichern. Ohne Aktivierung optionaler Dienste werden durch die eigene Anwendung keine Cookies gesetzt. Schriften und reguläre Produktbilder werden lokal ausgeliefert; dafür wird keine Verbindung zu Google Fonts aufgebaut.", "Links zu externen Angeboten öffnen deren Websites erst auf Ihre Aktion. Dort gelten deren eigene Speicher- und Cookie-Einstellungen. Die optionale 3D-Ansicht ist gesondert beschrieben."] },
      { title: "Optionale Reichweitenmessung", body: measurementCopy.de, links: [{ label: "Vercel Analytics: Datenschutz", href: "https://vercel.com/docs/analytics/privacy-policy" }] },
      { title: "NFC-/QR-Anfragen und Zwischenablage", body: ["Ihre Konfiguration und die eingegebenen Angaben werden zunächst nur im Arbeitsspeicher des Browser-Tabs zusammengefasst. Es gibt keinen Formularversand an einen eigenen Website-Server. Öffentliche Produktkennungen in Links enthalten keine persönlichen Anfrageangaben.", "Wenn Sie den vorbereiteten WhatsApp-Link öffnen, wird der Anfragetext bereits als Teil der URL an WhatsApp übergeben. Erst das Absenden in WhatsApp schickt die Nachricht an mich. Der vorbereitete E-Mail-Link übergibt den Inhalt an Ihr Mailprogramm. Beim Kopieren landet der Text in Ihrer Zwischenablage; deren Verwaltung oder Synchronisierung richtet sich nach Ihrem Gerät. Sie können den Text vor dem Versand ändern.", "Abgesehen von der beschriebenen Sprachübergabe verwirft eine neue Seitenladung den Zustand der Anwendung; Browser können Seitenzustände vorübergehend für Zurück-/Vorwärtsnavigation erhalten. Es werden keine Anfrageentwürfe auf diesem Website-Server gespeichert."] },
      { title: "Optionale 3D-Produktansicht", body: ["Erst durch die Auswahl «In 3D ansehen» lädt Ihr Browser die Software für die Ansicht und die ausgewählte Modelldatei. Diese Dateien werden von dieser Website ausgeliefert. Für die aktuellen Katalogmodelle werden keine Verbindungen zu Spline oder Google aufgebaut.", "Drehen und Vergrössern erfolgen lokal im Browser. Die 3D-Ansicht übermittelt keine Anfragefelder. Produktbilder und Anfrage funktionieren auch ohne Aktivierung der 3D-Ansicht. Beim Schliessen werden die Darstellung und ihre Grafikressourcen freigegeben."] },
      { title: "E-Mail, Telefon und soziale Kontaktwege", body: ["Bei einer Kontaktaufnahme werden beispielsweise Name, Kontaktdaten, Unternehmen, Nachrichten und vereinbarte Leistungsdaten bearbeitet. Das veröffentlichte E-Mail-Postfach wird über Gmail von Google bereitgestellt. Bei Nutzung dieses Kanals bearbeitet Google die Nachrichten und technische Daten nach den für den verwendeten Dienst geltenden Bedingungen. Google hat Gesellschaften in Irland und den USA; eine Bearbeitung in diesen Staaten ist möglich.", "Für WhatsApp-Nutzer in der europäischen Region ist WhatsApp Ireland Limited, Irland, zuständig; der Dienst nutzt auch Infrastruktur und verbundene Unternehmen in den USA. LinkedIn wird für Nutzer in der Schweiz durch LinkedIn Ireland Unlimited Company, Irland, bereitgestellt; Bearbeitungen können ebenfalls in den USA stattfinden. Diese Anbieter bearbeiten Daten auch für ihre eigenen Zwecke nach ihren jeweiligen Bedingungen.", "Sie können statt WhatsApp oder LinkedIn E-Mail oder Telefon verwenden. Eine Kontaktaufnahme erlaubt die Bearbeitung Ihrer Anfrage, ist aber keine pauschale Einwilligung in Werbenachrichten."], links: [{ label: "Google: Datenschutzerklärung", href: "https://policies.google.com/privacy?hl=de" }, { label: "WhatsApp: Datenschutz in der europäischen Region", href: "https://www.whatsapp.com/legal/privacy-policy-eea" }, { label: "LinkedIn: Datenschutz", href: "https://www.linkedin.com/legal/privacy-policy" }] },
      { title: "Empfänger und Bearbeitung im Ausland", body: ["Empfänger sind die jeweils genutzten Hosting-, Kommunikations- und optionalen Anzeigedienste sowie, soweit im Einzelfall erforderlich, mit einer Leistung beauftragte Dienstleister oder gesetzlich zuständige Stellen. Die oben genannten Dienste haben insbesondere Bezüge zur Schweiz, zu Irland und zu den USA. Ihre eigenen Anbieterinformationen beschreiben weitere eingesetzte Gesellschaften und Unterauftragnehmer.", "Im Ausland können andere Datenschutzregeln und behördliche Zugriffsmöglichkeiten bestehen. Ob ein angemessenes Schutzniveau, eine anwendbare Zertifizierung, vertragliche Garantien oder eine gesetzliche Ausnahme erforderlich ist, hängt vom Empfänger und Datenfluss ab. Aus der Erreichbarkeit eines Dienstes oder einem Klick folgt keine allgemeine Garantie eines bestimmten Datenschutzniveaus. Bei Fragen zu einem konkreten Kontaktkanal wenden Sie sich an die oben genannte Adresse."] },
      { title: "Aufbewahrung und Löschung", body: ["Kontakt- und Projektdaten werden aufbewahrt, soweit sie zur Bearbeitung der Anfrage, Vertragsabwicklung, Erfüllung gesetzlicher Pflichten oder Wahrung rechtlicher Ansprüche erforderlich sind. Geschäftsbücher und Buchungsbelege unterliegen grundsätzlich der gesetzlichen Aufbewahrungsfrist von zehn Jahren ab Ende des Geschäftsjahres. Das bedeutet nicht, dass jede beliebige Anfrage zehn Jahre gespeichert werden muss.", "Nicht mehr erforderliche Daten werden gelöscht oder anonymisiert, soweit keine Aufbewahrungspflicht oder erforderliche Beweissicherung entgegensteht. Technische Logs und Daten, die externe Anbieter für eigene Zwecke bearbeiten, unterliegen zusätzlich deren dienstspezifischen Aufbewahrungsregeln."] },
      { title: "Ihre Rechte", body: ["Im gesetzlichen Umfang können Sie Auskunft, Berichtigung und Löschung sowie gegebenenfalls Herausgabe oder Übertragung Ihrer Daten verlangen. Sie können eine Einwilligung für die Zukunft widerrufen und einer Bearbeitung widersprechen. Gesetzliche Pflichten, überwiegende Interessen und Rechte Dritter können diese Ansprüche begrenzen.", "Senden Sie Ihr Anliegen an hahn.silvan.work@gmail.com. Für eine sichere Zuordnung kann ein angemessener Identitätsnachweis erforderlich sein. Auskunft wird grundsätzlich innerhalb von 30 Tagen erteilt; über eine begründete Verzögerung werden Sie informiert. Sie können sich an den Eidgenössischen Datenschutz- und Öffentlichkeitsbeauftragten (EDÖB) wenden."], links: [{ label: "EDÖB: Datenschutz und Rechte", href: "https://www.edoeb.admin.ch/de/datenschutz" }] },
      { title: "Datensicherheit und Änderungen", body: ["HTTPS schützt die Verbindung zwischen Ihrem Browser und dieser Website. Technische und organisatorische Massnahmen sollen unbefugte Zugriffe und unbeabsichtigte Offenlegungen begrenzen; absolute Sicherheit kann kein Online-Dienst gewährleisten.", "Diese Erklärung wird bei Änderungen der eingesetzten Dienste oder Bearbeitungen angepasst. Die angegebene Fassung beschreibt den jeweiligen Stand; neue Zwecke bedürfen gegebenenfalls zusätzlicher Information."] },
    ],
  },
  en: {
    eyebrow: "Privacy", title: "How personal data is processed.",
    intro: "Information under the Swiss Federal Act on Data Protection (FADP) about this website, its concept demos and contacting SILVAN Digital Studio.",
    updatedLabel: "Updated", updated: "7 September 2026",
    sections: [
      { title: "Controller and scope", body: ["Silvan Hahn, Regensbergstrasse 23, 8113 Boppelsen, Switzerland. Privacy enquiries: hahn.silvan.work@gmail.com.", "This statement covers silvandigital.ch and the linked SILVAN concept demos Falkenried, Café & Konditorei Vogel, Steiner Bau and Salon Lumière on their Vercel addresses. Agreed client projects may require additional project-specific information."] },
      { title: "Purposes and necessary information", body: ["Data is processed to deliver the website securely, answer enquiries, prepare quotes, perform agreed services and meet legal obligations. You do not have to make an enquiry to browse. Without the necessary contact and project details, a requested quote or service may not be possible.", "The website has no user accounts, comments or customer database. It does not make automated decisions with legal effects about you. Please do not send passwords, identity documents, health information or other confidential client data through general contact channels."] },
      { title: "Hosting and technical access data", body: ["Vercel Inc., USA, delivers the website and demos through a distribution network. A visit involves processing information such as your IP address, time, requested address, technical browser/device information and, where applicable, the referring origin. This supports delivery, troubleshooting and protection against misuse.", "Processing may take place in the USA. Vercel describes international infrastructure and participation in the Swiss-U.S. Data Privacy Framework in its provider information. The particular processing also depends on the service used and its contractual terms."], links: [{ label: "Vercel privacy notice", href: "https://vercel.com/legal/privacy-notice" }] },
      { title: "Cookies, local storage and fonts", body: ["The website itself uses no cookies for advertising or profiling and does not save enquiry text in localStorage. Only an explicit language switch in the same tab places the NFC enquiry draft in sessionStorage for a single transfer: valid for at most two minutes and deleted on the next receipt attempt. Unconsumed data is deleted when the tab closes. There is no autosave. Without optional services being activated, the application itself sets no cookies. Fonts and regular product images are served locally, without a connection to Google Fonts.", "External links open other providers' websites only when you follow them. Their own storage and cookie settings then apply. The optional 3D viewer is described separately."] },
      { title: "Optional audience measurement", body: measurementCopy.en, links: [{ label: "Vercel Analytics privacy", href: "https://vercel.com/docs/analytics/privacy-policy" }] },
      { title: "NFC/QR enquiries and clipboard", body: ["Your configuration and entered information are initially assembled only in the browser tab's memory. There is no form submission to a website backend. Public product identifiers in links contain no personal enquiry information.", "Opening a prepared WhatsApp link already passes the enquiry text to WhatsApp as part of the URL. Sending the message there then sends it to me. A prepared email link passes the contents to your mail application. Copying puts the text in your clipboard, whose management and synchronisation depend on your device. You can edit the text before sending.", "Except for the language transfer described above, reloading discards the application's state; browsers may temporarily retain page state for back/forward navigation. This website server stores no enquiry drafts."] },
      { title: "Optional 3D product viewer", body: ["Selecting View in 3D loads the viewing software and the selected model file. These files are served by this website. The current catalogue models do not establish connections to Spline or Google.", "Rotation and zoom run locally in your browser. The viewer does not transmit enquiry fields. Product images and enquiries work without activating the 3D viewer. Closing the view releases its display and graphics resources."] },
      { title: "Email, telephone and social contact channels", body: ["Contact may involve your name, contact details, company, messages and agreed service information. The published mailbox uses Google's Gmail service. Using this channel involves Google processing messages and technical data under the terms of the service used. Google has entities in Ireland and the USA; processing in those countries is possible.", "WhatsApp Ireland Limited, Ireland, serves WhatsApp users in the European region; the service also uses infrastructure and associated companies in the USA. LinkedIn Ireland Unlimited Company, Ireland, serves users in Switzerland; processing may also take place in the USA. These providers also process data for their own purposes under their respective terms.", "You may use email or telephone instead of WhatsApp or LinkedIn. Contacting me allows your enquiry to be handled; it is not blanket consent to advertising messages."], links: [{ label: "Google privacy policy", href: "https://policies.google.com/privacy?hl=en" }, { label: "WhatsApp privacy policy for the European region", href: "https://www.whatsapp.com/legal/privacy-policy-eea" }, { label: "LinkedIn privacy policy", href: "https://www.linkedin.com/legal/privacy-policy" }] },
      { title: "Recipients and international processing", body: ["Recipients are the hosting, communication and optional viewing providers you use and, where required in a specific case, service providers performing an agreed task or legally competent authorities. The named services have connections in particular to Switzerland, Ireland and the USA. Their provider information describes other entities and subprocessors they use.", "Different data protection rules and government access powers may apply abroad. Whether adequacy, an applicable certification, contractual safeguards or a statutory exception is required depends on the recipient and data flow. A service being accessible, or clicking a link, does not provide a general guarantee of a particular level of protection. Please contact the address above with questions about a specific channel."] },
      { title: "Retention and deletion", body: ["Contact and project data is retained as necessary to handle the enquiry, perform contracts, meet legal obligations or protect legal claims. Accounting records and supporting documents are generally subject to a ten-year statutory retention period from the end of the financial year. This does not mean every enquiry must be kept for ten years.", "Data no longer needed is deleted or anonymised unless a retention obligation or necessary preservation of evidence applies. Technical logs and data processed by external providers for their own purposes also follow their service-specific retention rules."] },
      { title: "Your rights", body: ["To the extent provided by law, you may request access, correction and deletion and, where applicable, a copy or transfer of your data. You may withdraw consent for the future and object to processing. Legal duties, overriding interests and third-party rights may limit these rights.", "Send requests to hahn.silvan.work@gmail.com. Proportionate verification of your identity may be necessary. Access requests are generally answered within 30 days; you will be informed of a justified delay. You may contact the Swiss Federal Data Protection and Information Commissioner (FDPIC)."], links: [{ label: "FDPIC: data protection", href: "https://www.edoeb.admin.ch/en" }] },
      { title: "Security and changes", body: ["HTTPS protects the connection between your browser and this website. Technical and organisational measures aim to limit unauthorised access and accidental disclosure; no online service can guarantee absolute security.", "This statement is updated when services or processing change. The date identifies its current version; new purposes may require additional information."] },
    ],
  },
};
