import { cleanup, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, expect, it } from 'vitest';
import { ProductCatalog } from '../../src/components/products/ProductCatalog';
import { getContent } from '../../src/lib/locales';
import { getInquiryPreset } from '../../src/lib/inquiry-selection';
afterEach(()=>{cleanup();window.history.replaceState(null,'','/');});
it.each(['de','en'] as const)('guides application to family while preserving every variant and public selection in %s',async locale=>{
 const user=userEvent.setup(); const r=getContent(locale).reviews;
 window.history.replaceState(null,'','/reviews?category=reviews&model=review-round-black');
 render(<ProductCatalog locale={locale} products={r.catalog} categories={r.categories} labels={{category:r.catalogLabel,categoryPrompt:r.categoryPrompt,productSingular:r.productSingular,productPlural:r.productPlural,view3d:r.view3dLabel,comingSoon:r.comingSoonLabel,previousProduct:r.previousProductLabel,nextProduct:r.nextProductLabel,productPosition:r.productPositionLabel,productPositionOf:r.productPositionOfLabel,close:r.close3dLabel,loading:r.loading3dLabel,error:r.error3dLabel,retry:r.retry3dLabel,interact:r.interact3dLabel}}/>);
 const count=()=>document.querySelectorAll('[data-product-index]').length;
 expect(count()).toBe(r.catalog.filter(p=>p.category==='reviews').length);
 const stand=screen.getByRole('button',{name:locale==='de'?'Aufsteller':'Stand'});stand.focus();await user.keyboard('{Enter}');
 expect(stand).toHaveAttribute('aria-pressed','true');expect(count()).toBe(r.catalog.filter(p=>p.category==='reviews'&&getInquiryPreset(p.id)?.product==='standard-stand').length);
 expect(window.location.search).toContain('model=review-round-black');
 await user.click(screen.getByRole('button',{name:locale==='de'?'Flache Karte':'Flat card'}));
 expect(count()).toBe(r.catalog.filter(p=>p.category==='reviews'&&getInquiryPreset(p.id)?.product!=='standard-stand').length);
 await user.click(screen.getByRole('button',{name:locale==='de'?'Alle Produkttypen':'All product types'}));expect(count()).toBe(r.catalog.filter(p=>p.category==='reviews').length);
 await user.selectOptions(screen.getByRole('combobox'), 'chips');expect(screen.getByRole('button',{name:locale==='de'?'Klebe-Chip':'Adhesive chip'})).toBeVisible();expect(count()).toBe(r.catalog.filter(p=>p.category==='chips').length);
});
